<?php

$this->widget ( 'ext.mediaElement.MediaElementPortlet',array (
    'model' => $value,
    'url' => "http://localhost/framework/sgci/proyectos/video/$value->nombmult",
    'mimeType' =>'video/mp4',
    'autoplay'=>false,
));

$this->widget('ext.evfeplayer.eVFEplayer', array(
    'filename'=>$nombre = str_replace( ".$value->extension", '', $value->nombmult),
    'altmsg'=>'...some text...',
    'baseurl'=>"http://localhost/framework/sgci/proyectos/video",
    'autoplay'=>false,
    'controls'=>true,
    'width'=>480,
    'height'=>356,
));

$this->widget('application.extensions.videojs.EVideoJS', array(
    'options' => array(
        'id' => false, // Unique identifier, is autogenerated by default, useful for jQuery integrations.
        'width' => 320, // Video and poster width in pixels
        'height' => 240, // Video and poster height in pixels
        'poster' => false, // Poster image absolute URL
        'video_mp4' => "http://localhost/framework/sgci/proyectos/video/$value->nombmult", // Absolute URL of the video in MP4 format
        'video_ogv' => false, // Absolute URL of the video in OGV format
        'video_webm' => false,// Absolute URL of the video in WebM format
        'flash_fallback' => true, // Use Flash fallback player ?
        'flash_player' => '', // Address of custom Flash player to use as fallback
        'controls' => true, // Show controls ?
        'preload' => true, // Preload video content ?
        'autoplay' => false,// Autostart the playback ?
        'support' => true, // Show VideoJS support link ?
        'download' => true, // Show video download links ?
    ),
));

?>
