<?php
/* @var $this MultimediaController */
/* @var $multimedia Multimedia */
?>

<h4 class="center">Videos</h4>
<?php
$resultado = str_replace( "/", '', Yii::app()->request->baseUrl);
//echo $resultado; ?>
<div class="row">
	<div class="col m12">
<?php
//$nombmult = str_replace( ".$value->extension", '', $value->nombmult)
foreach ($multimedia as $value) {
	if ($value->tipomult == 'video') {
?>
	<div class="col m6">
		<div class="row">
			<?php
			$this->widget('ext.evfeplayer.eVFEplayer', array(
				'filename'=>$nombre = str_replace( ".$value->extension", '', $value->nombmult),
				//'altmsg'=>$value->nombmult,
				'baseurl' => Yii::app()->request->baseUrl.$value->ruta,
				'autoplay'=>false,
				'controls'=>true,
				'width'=>272,
				'height'=>153,
			));
			/*$this->widget('application.extensions.videojs.EVideoJS', array(
			    'options' => array(
			        'id'				=> false, // Unique identifier, is autogenerated by default, useful for jQuery integrations.
			        'width'				=> 272, // Video and poster width in pixels //413 para que este acorde al espacio en pantalla
			        'height'			=> 153, // Video and poster height in pixels
			        'poster'			=> false, // Poster image absolute URL
			        'video_mp4'			=> Yii::app()->request->baseUrl.$value->ruta, // Absolute URL of the video in MP4 format
			        'video_ogv'			=> false, // Absolute URL of the video in OGV format
			        'video_webm'		=> false,// Absolute URL of the video in WebM format
			        'flash_fallback' 	=> true, // Use Flash fallback player ?
			        'flash_player'		=> '', // Address of custom Flash player to use as fallback
			        'controls'			=> true, // Show controls ?
			        'preload'			=> true, // Preload video content ?
			        'autoplay'			=> false,// Autostart the playback ?
			        'support'			=> true, // Show VideoJS support link ?
			        'download'			=> true, // Show video download links ?
			    ),
			));*/
			?>
		</div>
		<div class="row">
			<?php
			echo "<a class='blue-text'>Proyecto: </a>". CHtml::encode($value->multpro->nombpro)."<br>";
			echo "<a class='blue-text'>Creador: </a>". CHtml::encode($value->multpro->creador)."<br>";
			echo "<a class='blue-text'>Video: </a>". CHtml::encode($value->nombmult)."<br>";
			?>
			<div class="center-align">
				<?php
				$image = CHtml::image(Yii::app()->baseUrl."/fonts/download.svg", 'link', array('title'=>'Descargar'));
				echo CHtml::link(
					"Descargar ". $image,
					array('/multimedia/descargar'),
					array(
						'submit'=>array('/multimedia/descargar'),
						'params'=>array('m'=>$value->idmult),//no es necesario
						'target'=>'_blank',
						//'id'=>'btnpdfs',
						'class'=>'green-text'
					)
				);?>
			</div>
		</div>
	</div>
<?php
	}
}
?>
</div>
</div>
