<?php
/* @var $this MultimediaController */
/* @var $model Multimedia */

$this->breadcrumbs=array(
	'Proyecto Digitales'=>array('index'),
	'Detalles',
);

if(Yii::app()->user->checkAccess('tutor')){
    $this->menu=array(
        array('label'=>"<i class='small material-icons'>home</i>", 'url'=>array('index'),'linkOptions'=>array('class'=>'btn-floating blue'))
    );
}

if (Yii::app()->user->checkAccess('admin') || Yii::app()->user->checkAccess('administrador')) {
    $this->menu=array(
        array('label'=>"<i class='small material-icons'>home</i>", 'url'=>array('index'),'linkOptions'=>array('class'=>'btn-floating blue')),
    );
}

$resultado = str_replace( "/", '', Yii::app()->request->baseUrl);
?>

<h4 class="center-align">Detalle del Proyecto "<?php echo $multimedia->multpro->nombpro; ?>"</h4>

<div class="valign-wrapper row">
	<div class="col s12 pull-l3 l6">

		<?php if ($multimedia->tipomult == 'audio'){ ?>
			<div class="col">
				<?php $this->widget('ext.mediaElement.MediaElementPortlet',array(
					'model' => $multimedia,
					'url' => Yii::app()->request->baseUrl.$multimedia->ruta.$multimedia->nombmult,
					'mimeType' =>'audio/mp3',
					'autoplay'=>false,
				));	?>
				<div class="center-left">
					<p><?php echo "<a class='blue-text'>Nombre del Proyecto: </a>" . CHtml::encode($multimedia->multpro->nombpro);?></p>
					<p><?php echo "<a class='blue-text'>Creador: </a>" . CHtml::encode($multimedia->multpro->creador);?></p>
					<p><?php echo "<a class='blue-text'>Audio: </a>" . CHtml::encode($multimedia->nombmult); ?></p>
				</div>
			</div>
		<?php }else if($multimedia->tipomult == 'video'){ ?>
			<div class="">
				<?php
				$this->widget('ext.evfeplayer.eVFEplayer', array(
					'filename'=>$nombre = str_replace( ".$multimedia->extension", '', $multimedia->nombmult),
					'altmsg'=>$multimedia->nombmult,
					'baseurl'=>Yii::app()->request->baseUrl.$multimedia->ruta,
					'autoplay'=>false,
					'controls'=>true,
					'width'=>500,
					'height'=>340,
				));
				/*$this->widget('application.extensions.videojs.EVideoJS', array(
				    'options' => array(
				        'id' => false, // Unique identifier, is autogenerated by default, useful for jQuery integrations.
				        'width' => 500, // Video and poster width in pixels
				        'height' => 340, // Video and poster height in pixels
				        'poster' => false, // Poster image absolute URL
				        'video_mp4' => $resultado.$multimedia->ruta.$multimedia->nombmult, // Absolute URL of the video in MP4 format
				        'video_ogv' => false, // Absolute URL of the video in OGV format
				        'video_webm' => false,// Absolute URL of the video in WebM format
				        'flash_fallback' => true, // Use Flash fallback player ?
				        'flash_player' => '', // Address of custom Flash player to use as fallback
				        'controls' => true, // Show controls ?
				        'preload' => true, // Preload video content ?
				        'autoplay' => false,// Autostart the playback ?
				        'support' => true, // Show VideoJS support link ?
				        'download' => true, // Show video download links ?
				    ),
				));*/
				?>
				<div class="center-left">
					<p><?php echo "<a class='blue-text'>Nombre del Proyecto: </a>" . CHtml::encode($multimedia->multpro->nombpro);?></p>
					<p><?php echo "<a class='blue-text'>Creador: </a>" . CHtml::encode($multimedia->multpro->creador);?></p>
					<p><?php echo "<a class='blue-text'>Video: </a>" . CHtml::encode($multimedia->nombmult); ?></p>
				</div>
			</div>
		<?php } ?>

	</div>
</div>


<div class="row">
    <div class="center-align">
        <?php
        $libros = CHtml::image(
            Yii::app()->request->baseUrl.'/fonts/left2.svg',
            'left',
            array('id'=>'regresar','width'=>'35px','title'=>'regresar','class'=>'arrow-left')
        );
        echo CHtml::link( $libros, array("/multimedia/index") );
        ?>
    </div>
</div>

<?php /*$this->widget('zii.widgets.CDetailView', array(
	'data'=>$multimedia,
	'attributes'=>array(
		'idmult',
		'nombmult',
		'extension',
		'tipomult',
		'tamanio',
		'ruta',
	),
));*/ ?>

<script type="text/javascript">
	<?php if(Yii::app()->user->hasFlash('multimediaC')){ ?>
		window.addEventListener('load', function(){
			Swal.fire({
				icon: 'success',
				title: "<?php echo Yii::app()->user->getFlash('multimediaC')?>",
				showConfirmButton: false,
				timer: 3000 // es ms (mili-segundos)
			});
		});
	<?php } ?>
</script>
